### ISSUE TITLE
ATF Slide Disappearing

### ISSUE THREAD

**Issue by andrewatduckpin** [Dental-Revenue/Codebase-2-Dev#16]
Reported by nancy on site: http://drgittleman.wpengine.com/

Description of issue:
When the site is compressed down to the mobile settings and them resized out to desktop the main slider area image/ATF disappears.

**Comment by zachatduckpin** [comment]
Got the slider to not disappear on resize, but its buggy after resizing back out. Will keep at it tomorrow.

[https://drcodebase2.wpengine.com/](https://drcodebase2.wpengine.com/)

**Comment by zachatduckpin** [comment]
Was attempting to slick/unslick the slides of the fold_slices module on mobile/desktop, but I guess there's a known issue with slick removing slides from the DOM on unslick (https://github.com/kenwheeler/slick/issues/2434) 

So I ended up having to create two separate loops/containers for the slides to show/hide on mobile/desktop
