### ISSUE TITLE
Move contents from parent style.css to partials

### ISSUE THREAD

**Issue by andrewatduckpin** [Dental-Revenue/Codebase-2-Dev#2]
Let's move lines 9 - 74 of codebase 2 main style.css into one or more partials that get compiled into the real stylesheet.

The only thing we need to keep in this file is lines 1- 7 which are required for WP theme and Github Updater to work properly.

Partial suggestions might be:

**Comment by zachatduckpin** [comment]
Looks like some of this stuff is already in /vendor/_wpdefaults.scss, /vendor/_normalize.scss or /general/_grid.scss. I'll disperse the styles under CLEARFIX, HACKS AND OVERRIDES, and INVALID FIELDS to partials that make sense.
