### ISSUE TITLE
No support for ATF Videos

### ISSUE THREAD

**Issue by Dchyk** [Dental-Revenue/Codebase-2-Dev#32]
As far as I can tell the scripts for resizing ATF videos are not present anywhere in CB2. This results in behavior like this when using videos as slider backgrounds: 

![Screen Shot 2019-04-17 at 2 11 59 PM](https://user-images.githubusercontent.com/25135946/56310861-d8737500-611a-11e9-8623-51c985bc77ec.png)

In previous codebase versions, there is a function called "covervid" that handles this. Should probably add that back.

**Comment by andrewatduckpin** [comment]
closing as issue exists (#28 )
