### ISSUE TITLE
Add testimonials template

### ISSUE THREAD

**Issue by andrewatduckpin** [Dental-Revenue/Codebase-2-Dev#34]
Add a testimonials page template. Include "live" google reviews if google place id is present in theme settings.

See CB1 for reference.

**Comment by andrewatduckpin** [comment]
Reference:
https://www.dechtermoy.com/our-dentist-office/testimonials/

**Comment by zachatduckpin** [comment]
I've added in the testimonials page template:
http://drcodebase2.wpengine.com/testimonials/

If testimonials from both the live reviews and the testimonials CPT are present like in the example should one or the other appear first or not at all? Right now live reviews are listed first
