### ISSUE TITLE
Logo Enlargement

### ISSUE THREAD

**Issue by ghost** [Dental-Revenue/Codebase-2-Dev#47]
Make the logo 150px by default in the source code, instead of 102px.

**Comment by zuriBarnes** [comment]
Paul do you know which scss file we should edit for the logo? 

this?
assets\stylesheets\style.scss

also noticed this.
assets\stylesheets\layout\_header.scss

**Comment by ghost** [comment]
Sure, good question! The style.scss is only for importing all the other scss files, so we won't ever have to edit that directly, unless we add a new template. In scss, a template is any file that begins with a "_", like all those layout files. So yeah, you nailed it, the _header.scss is the file. You can search for that default value that we see for the logo, 102px, and change that. If we really want to be complete, we should find all the breakpoints that this file uses, look at the logo in those sizes, and change the value for each breakpoint. But we can also do that on a later patch, it's up to you!

**Comment by zuriBarnes** [comment]
Ok, cool. Yeah, I thought about breakpoints, and also the 4 header styles.

I know we still be asked to enlarge or reduce per client/emily, request
after these edits. No two logos are same. So, is it worth it?

**Comment by ghost** [comment]
I agree that we'll always have to change it on mobile. What I've seen with every client, is that I make that 102px value 150px, like every time, so maybe that's worth changing?

**Comment by ghost** [comment]
If you want to make a case to Nancy that we don't need this feature, I won't stop you. Ultimately, I'm probably going to create a new header that will use something like vh or % instead of pixels, so this won't be as much of a problem.

**Comment by zuriBarnes** [comment]
I think we should hold of on this for now.
