### ISSUE TITLE
SIS Excerpts

### ISSUE THREAD

**Issue by ghost** [Dental-Revenue/Codebase-2-Dev#735]
Top of video gets cut off in x-large screens
When button on video- in mobile- button drops- too much padding
In desktop/ large screen- video height gets cut off 
Text padding field was removed- add it back?
Mobile- too much top and bottom spacing 
Mobile- images full width
Mobile- boxes should be full width
Mobile- text should be consistent with size in desktop to mobile 
Title + Subtitle doesn’t pull above form in desktop- does show in mobile

**Comment by ghost** [comment]
@eplumb897 Would you mind attaching a test video file here that I can use for this module?

**Comment by ghost** [comment]
Also we may need to hop on a call and get some clarification on this, I have a few questions.

**Comment by eplumb897** [comment]
There should be video files in media gallery

**Comment by ghost** [comment]
@eplumb897 For the title and subtitle on the form, I'm not seeing it in mobile or desktop, which makes sense because there's no code for that! Which of the following text options do you want to show up above the form?

- [x] Title
- [x] Subtitle
- [x] Excerpt
- [ ] Phone Number
- [ ] Address
- [ ] Button
- [ ] Logo

**Comment by eplumb897** [comment]
the check boxes are fun!

**Comment by ghost** [comment]
I'm glad they actually worked as expected, I wasn't sure. I'll work on this today and some other things.

**Comment by ghost** [comment]
### 1. Top of video gets cut off in x-large screens.
2560x1600
![SIS Video 2560x1600](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/99916831/6855a881-6527-4ef0-9e22-8a3c09f8b147)
2560x1920
![SIS Video 2560x1920](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/99916831/dea567ad-2929-4bac-828f-f60dd583dd67)
3840x2160
![Sis Video 3840x2160](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/99916831/fb982568-5c6f-481c-94e8-386611da9db6)
### 2. When button on video- in mobile- button drops- too much padding
I worked on positioning the video and the button for a while, but it occurred to me that video shouldn't really play like that on tablet any more than mobile. What I ended up doing was switching to picture/no video as soon as it gets below 1,200 pixels, and just making sure the video is well positioned on anything above 1,200 pixels. That allowed me to just work on styling the button on mobile sizes by itself. I removed any padding on mobile, but I did leave a top and bottom margin. In the pictures below, the padding below the button is on the module itself, and can be removed by you in the admin dashboard if you like.
Tablet on Chrome
![SIS Button Galaxy Tab Chrome](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/99916831/87ee67d6-9e93-498d-a1e9-2fade8d9ba36)
Mobile on Safari
![SIS Button iPhone 14 Plus](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/99916831/4b288cd5-4d4e-485e-9bd3-8ddc75ca1991)
### 3. Duplicate of 1
### 4. Text padding field was removed- add it back?
![Left Padding Field](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/99916831/ff724c1d-b9f3-40aa-92cf-766ae7877cde)
![Padding Value](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/99916831/b06da953-4477-49d5-b6f7-75a49c74cba4)
![Right Padding Field](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/99916831/6b963558-6c93-4b2e-9c07-e08112effc05)
### 5. Mobile- too much top and bottom spacing
I resolved this by resetting the padding to only 35 pixels of top padding on mobile and tablet, which we agreed on as a working solution on the phone on 9/8.
### 6. Mobile- images full width
I restyled the images in this module so that they are always full width on mobile and not distorted (meaning their height is automatically set based on being full width). I put rules in for this, but they aren't showing up on Browser Stack yet, but I confirmed these with you on the phone on 9/8 by showing you how the rules would look on an iPhone.
### 7. Mobile- boxes should be full width
Restyled so that a text box is always full width on mobile.
![SIS Mobile Text Width Text Only](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/99916831/5837c786-1b16-47d6-b861-19071381e365)
### 8. Mobile- text should be consistent with size in desktop to mobile
Something else we discussed on the phone on 9/8 and 9/5. The solution at the moment is to set a max font-size in mobile, with the understanding that using the wysiswyg editor for those excerpts has many advantages, but the disadvantage that whatever is put into that excerpt box will look exactly the same on all sizes, so we have to just style the child theme for mobile in this instance.
### 9. Title + Subtitle doesn’t pull above form in desktop- does show in mobile
iPhone 14 Plus
![Form Title Subtitle Excerpt iPhone 14 Plus](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/99916831/864bff4b-a4ab-498a-9502-295f11ac0f85)
Desktop Chrome
![SIS Form Title Subtitle Excerpt Desktop Chrome](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/99916831/922e8f95-dea3-4884-9957-4c562f62a69a)
