### ISSUE TITLE
Add New Module Features To All Internal Modules

### ISSUE THREAD

**Issue by ghost** [Dental-Revenue/Codebase-2-Dev#739]
**Is your feature request related to a problem? Please describe.**
New features have been added to various homepage modules (static image split, fold slider, etc...) that need to also exist on internal modules.

**Describe the solution you'd like**
Copy the module code for every internal page, and confirm that all is working as expected.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by eplumb897** [comment]
Going to move this to an Internal Module project

**Comment by eplumb897** [comment]
Let's wait on this until we have all functionality/ responsive issues sorted out

**Comment by ghost** [comment]
@eplumb897 I'm unable to reproduce this on any tablet or phone size in browser stack, or in the browser itself. If this is referring to the fact that you can resize a browser and it keeps the styles of the size you started on, there's not much I can do about that, but let me know if there's something else going on.
