### ISSUE TITLE
Text/ Video: Responsive Issue

### ISSUE THREAD

**Issue by eplumb897** [Dental-Revenue/Codebase-2-Dev#745]
Video should flip to image in mobile- Video does not flip to image in mobile- video and image are both showing in mobile and ipad sized

**Expected behavior**
Video should remain fully visible in desktop
Video should remain fully visible in ipad
Video should flip to image in mobile

[All sizes image/ video should remain fully visible 
)
**Screenshots**

![Image](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/101214859/c4368d8a-dd78-4b53-80ad-7c8a4ed96e3d)

**Additional context**

**Comment by eplumb897** [comment]
Hey Paul- this is listed as "Ready" does this mean edits are visible on the testing site for me to view?

**Comment by ghost** [comment]
I've been using Ready to mean ready to be worked on but no one has started yet. We should probably make sure we both have the same process in mind, and the statuses for each project can be customized.

**Comment by eplumb897** [comment]
okay- thank you!

**Comment by eplumb897** [comment]
I will make a list of statuses and the meanings so we can standardize

**Comment by eplumb897** [comment]
![Image](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/101214859/ea8ac096-f0bd-48cb-99e8-f0f959b34d82)

**Comment by eplumb897** [comment]
showing just image now- which is good- but image cut off- need to increase height. 

Images in split modules below- stretched out and distorted- let's format like this one just with taller height

The space which the image falls in should be consistent

**Comment by eplumb897** [comment]
Check out static image split image proportions in mobile here- https://www.northboroughmadentist.com/

or here-  https://www.broadwaydentaltexas.com/


or here- https://haddad2023.wpengine.com/
