### ISSUE TITLE
Text/ Text W/ Bck Img Grid Tst Overlap Issue

### ISSUE THREAD

**Issue by eplumb897** [Dental-Revenue/Codebase-2-Dev#746]
Text/ Text with background Image
overlap with grid testimonial- Desktop

Overlap works- but it sort of pushes the filter up- see screenshot

**Expected behavior**
boxes should overlap image split module with out effective the module above it
**Screenshots**

![Image](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/101214859/63482a90-4932-43a9-ba09-3df28efea990)

**Comment by eplumb897** [comment]
see where the boxes overlay background- it is lighter in the verticle space the boxes take up- should look same as background above- does this make sense?

**Comment by ghost** [comment]
@eplumb897 This isn't actually forhte static image split module, right, it's for reviews testimonials grid? I like the idea of having projects for each module, but we'll have to create them as they come up. If you end up creating any new projects, would you mind copying the CB2 project as a template to make the new one? That way we have all the statuses consistent across projects.

The issue makes sense, I'll have to see if there's some kind of overlay on the module above.

**Comment by ghost** [comment]
Or is this Static Block List?

**Comment by eplumb897** [comment]
It's grid testimonial- overlapping a static image split

**Comment by ghost** [comment]
I know this is a bit finnicky, but can we use project names that match the module names? I made one for Reviews Testimonials Grid and added it.

**Comment by eplumb897** [comment]
Okay- that's fine, but I don't want us running in opposite directions. I'll set up the projects over the next few days - I will name them to match the modules

**Comment by ghost** [comment]
Awesome, thanks!

**Comment by ghost** [comment]
Per meeting with @eplumb897, I will set the max-height on each static image split side to be 58 viewport heights, and remove the left positioning of videos on x-large screen sizes.

**Comment by ghost** [comment]
After conversation with @eplumb897, closing this ticket because it is editable in the admin dashboard.
