### ISSUE TITLE
Issues: Image Split 9.19

### ISSUE THREAD

**Issue by eplumb897** [Dental-Revenue/Codebase-2-Dev#775]
When you're back let's jump on a call to discuss

![Image](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/101214859/84777d9b-7c9e-42f3-88dd-b52908358f2f)
![Image](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/101214859/a2a62ad2-a813-4280-9273-34eaab43f956)
![Image](https://github.com/Dental-Revenue/Codebase-2-Dev/assets/101214859/7d1400c3-96ad-45ba-bf87-c0ec9d156d0f)

**Comment by ghost** [comment]
Per meeting with @eplumb897, I will set the max-height on each static image split side to be 58 viewport heights, and remove the left positioning of videos on x-large screen sizes.

**Comment by ghost** [comment]
Duplicate of #746
