### ISSUE TITLE
Static_Image_Split: Form

### ISSUE THREAD

**Issue by zuriBarnes** [Dental-Revenue/Codebase-2-Dev#92]
DR forms only picks up a name from the following three designations:  "name", "firstname", "lastname".   "name"  will take precedence over the other 2

Currently, "FullName" is in the code. You would have it set to "AdsNext-FullName". 

Lets use "name" for the default instead

**Comment by ghost** [comment]
@zuriBarnes Do you already have a working branch on this one, or can I create one?
